FROM python:latest
COPY . .
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app
COPY . .
RUN apt-get update

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
